import apiClient from '../api/client';

export const reportService = {
  getReports: async (params = {}) => {
    // 100% 자동 생성 모드: 감지 기록(Events)을 무조건 신고 문서로 1:1 자동 렌더링
    const eventsRes = await apiClient.get('/api/events');
    const events = eventsRes.data?.data || eventsRes.data || [];
    return events.map((ev, idx) => ({
      id: `REP-${ev.event_id || ev.id || idx}`,
      report_id: `REP-${ev.event_id || ev.id || idx}`,
      detection_id: ev.event_id || ev.id,
      event_id: ev.event_id || ev.id,
      type: ev.obstacle_type || ev.type || ev.event_type || '위험 요소',
      event_type: ev.obstacle_type || ev.type || ev.event_type || '위험 요소',
      title: `도로 위험 감지 자동 보고서 (${ev.obstacle_type || '위험 요소'})`,
      subject: `도로 위험 감지 자동 보고서 (${ev.obstacle_type || '위험 요소'})`,
      status: '신고 완료',
      author: 'SYSTEM',
      created_by: 'SYSTEM',
      created_at: ev.first_detected_at || ev.last_detected_at || ev.detected_at || ev.created_at || new Date().toISOString(),
      address: ev.address || ev.location || '위치 정보 없음',
      latitude: ev.latitude,
      longitude: ev.longitude
    }));
  },
  getReport: async (id) => {
    // 단건 조회도 무조건 감지 기록(Events)에서 가져옴
    const eventsRes = await apiClient.get('/api/events');
    const events = eventsRes.data?.data || eventsRes.data || [];
    const ev = events.find(e => `REP-${e.event_id||e.id}` === id || String(e.event_id) === String(id) || String(e.id) === String(id)) || events[0];
    if (!ev) return null;
    return {
      id: `REP-${ev.event_id || ev.id || 1}`,
      report_id: `REP-${ev.event_id || ev.id || 1}`,
      detection_id: ev.event_id || ev.id,
      event_id: ev.event_id || ev.id,
      type: ev.obstacle_type || ev.type || ev.event_type || '위험 요소',
      event_type: ev.obstacle_type || ev.type || ev.event_type || '위험 요소',
      title: `도로 위험 감지 자동 보고서 (${ev.obstacle_type || '위험 요소'})`,
      subject: `도로 위험 감지 자동 보고서 (${ev.obstacle_type || '위험 요소'})`,
      status: '신고 완료',
      author: 'SYSTEM',
      created_by: 'SYSTEM',
      created_at: ev.first_detected_at || ev.last_detected_at || ev.detected_at || ev.created_at || new Date().toISOString(),
      address: ev.address || ev.location || '위치 정보 없음',
      latitude: ev.latitude,
      longitude: ev.longitude
    };
  },
  createReport: async (eventId) => {
    return { success: true, autoGenerated: true };
  }
};
