import apiClient from '../api/client';
import { detectionService } from './detectionService';

export const reportService = {
  getReports: async (params = {}) => {
    // 100% 자동 생성 모드: 감지 기록(Events)을 무조건 신고 문서로 1:1 자동 렌더링
    const events = await detectionService.getDetections(params);
    return events.map((ev, idx) => ({
      id: `REP-${ev.event_id || ev.id || idx}`,
      report_id: `REP-${ev.event_id || ev.id || idx}`,
      detection_id: ev.event_id || ev.id,
      event_id: ev.event_id || ev.id,
      type: ev.obstacle_type || ev.type || ev.event_type || '위험 요소',
      event_type: ev.obstacle_type || ev.type || ev.event_type || '위험 요소',
      title: `도로 위험 감지 자동 보고서 (${ev.obstacle_type || '위험 요소'})`,
      subject: `도로 위험 감지 자동 보고서 (${ev.obstacle_type || '위험 요소'})`,
      status: '신고 완료',
      author: 'SYSTEM',
      created_by: 'SYSTEM',
      created_at: ev.first_detected_at || ev.last_detected_at || ev.detected_at || ev.created_at || new Date().toISOString(),
      address: ev.address || ev.location || '위치 정보 없음',
      latitude: ev.latitude,
      longitude: ev.longitude,
      image_url: ev.image_url,
      images: ev.images || ev.detection_images,
      detection_images: ev.detection_images
    }));
  },
  getReport: async (id) => {
    const numericId = String(id).replace(/[^0-9]/g, '');
    let det;
    try {
      det = await detectionService.getDetection(numericId || id);
    } catch (e) {
      console.error(e);
    }
    
    if (!det) {
      const events = await detectionService.getDetections();
      det = events.find(e => {
        const eId = String(e.event_id || e.id).replace(/[^0-9]/g, '');
        return eId === numericId && eId !== '';
      }) || events[0];
    }
    if (!det) return null;

    return {
      id: `REP-${det.event_id || det.id || 1}`,
      report_id: `REP-${det.event_id || det.id || 1}`,
      detection_id: det.event_id || det.id,
      event_id: det.event_id || det.id,
      type: det.obstacle_type || det.type || det.event_type || '위험 요소',
      event_type: det.obstacle_type || det.type || det.event_type || '위험 요소',
      title: `도로 위험 감지 자동 보고서 (${det.obstacle_type || '위험 요소'})`,
      subject: `도로 위험 감지 자동 보고서 (${det.obstacle_type || '위험 요소'})`,
      status: '신고 완료',
      author: 'SYSTEM',
      created_by: 'SYSTEM',
      created_at: det.first_detected_at || det.last_detected_at || det.detected_at || det.created_at || new Date().toISOString(),
      address: det.address || det.location || '위치 정보 없음',
      latitude: det.latitude,
      longitude: det.longitude,
      image_url: det.image_url,
      images: det.images || det.detection_images,
      detection_images: det.detection_images
    };
  },
  createReport: async (eventId) => {
    return { success: true, autoGenerated: true };
  }
};
